###Criando um novo carrinho
POST http://localhost:3000/carts HTTP/1.1
content-type: application/json

{
    "productQuantity": 1 ,
    "stockId": 1 
}


###Listando todos os carrinhos
GET http://localhost:3000/carts HTTP/1.1
content-type: application/json


### Listando um carrinho pelo ID
GET http://localhost:3000/carts/1 HTTP/1.1
content-type: application/json

###Deletando um carrinho pelo ID
DELETE http://localhost:3000/carts/1 HTTP/1.1
content-type: application/json

###Atualizando um carrinho pelo ID
PUT http://localhost:3000/carts/1 HTTP/1.1
content-type: application/json

{
    "productQuantity": ,
    "stockId": 
}

