###Criando um novo pagamento
POST http://localhost:3000/payments
Content-Type: application/json

{
  "pix": "",
  "credit_card": "",
  "paymentStatus": ,
  "value": ,
  "user": "",
  "date": "",
  "order_detail": ""
}

###Listando todos os pagamentos
GET http://localhost:3000/payments
Content-Type: application/json
