###Criando um novo pagamento
POST http://localhost:3000/payments
Content-Type: application/json

{
  "pix": "",
  "credit_card": "",
  "paymentStatus": true,
  "value": 70.00,
  "user": "salve",
  "date": "2025-09-17",
  "order_detail": "com muito chocolate"
}

###Listando todos os pagamentos
GET http://localhost:3000/payments
Content-Type: application/json

###Listando todos os pagamentos
GET http://localhost:3000/payments?user=salve
Content-Type: application/json

### da o show em um pagamento
GET http://localhost:3000/payments/4
Content-Type: application/json

###Update
PUT http://localhost:3000/payments
Content-Type: application/json

###Delete
DELETE http://localhost:3000/payments/3
Content-Type: application/json