POST http://localhost:3000/rules HTTP/1.1
content-type: application/json

{
  "stockControl": ,
  "lowStockAlert": ,
  "registerProduct": ,
  "disableProduct": ,
  "editStock": ,
  "usersRegistered": ,
  "stockList": ,
  "editUser": ,
  "dashboardInvoicing": ,
  "recipes": ,
  "pricing": ,
  "newOffer": ,
  "shopCart": ,
  "myPurchases": ,
  "profile": ,
  "sumStock": ,
  "disableUser": ,
  "purchasingReport": ,
  "userList": ,
  "userStatus": ,
  "productStatus": 
}
