POST http://localhost:3000/rules HTTP/1.1
content-type: application/json

{
  "stockControl": true,
  "lowStockAlert": true,
  "registerProduct": true,
  "disableProduct": false,
  "editStock": true,
  "usersRegistered": true,
  "stockList": true,
  "editUser": true,
  "dashboardInvoicing": true,
  "recipes": true,
  "pricing": true,
  "newOffer": true,
  "shopCart": true,
  "myPurchases": true,
  "profile": true,
  "sumStock": true,
  "disableUser": false,
  "purchasingReport": true,
  "userList": true,
  "userStatus": true,
  "productStatus": true
}
