###Criando um estoque / Adicionando um produto ao estoque
POST http://localhost:3000/stocks HTTP/1.1
content-type: application/json
        
        {
        "productName": "teste",
        "productType": "teste",
        "productPrice": 9, 
        "isInStock": true,
        "amountInStock": 10 
        }

###Listando todos os estoques
GET http://localhost:3000/stocks HTTP/1.1
content-type: application/json
