POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "pass": "teste",
    "email": "teste@teste.com",
    "name": "teste",
    "birth": "2005-07-17",
    "creditCard": "1234567890123456",
    "address": "teste",
    "phone": "16999999999",
    "permission": true
}
