POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "pass": "bolo123",
  "email": "maria@doces.com",
  "name": "Maria dos Doces",
  "birth": "1985-06-15",
  "creditCard": "5555-6666-7777-8888",
  "address": "Rua dos Sabores, 45, Cidade X",
  "phone": "99988-7766",
  "permission": true
}


